# Generated by Django 4.2 on 2023-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_account',
            options={},
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
